### Part 1: Theoretical Questions:

#### 1. What are the different data structures used in Tensorflow?. Give some examples.

TensorFlow primarily relies on two main data structures:

1. **Tensors:** Tensors are multi-dimensional arrays that can hold data of various data types. They are the fundamental building blocks of TensorFlow. Tensors can be scalars (0-dimensional), vectors (1-dimensional), matrices (2-dimensional), or higher-dimensional arrays. Tensors are used to represent input data, intermediate computations, and model parameters. Examples include:

   - Scalar: `tf.constant(5)`
   - Vector: `tf.constant([1, 2, 3])`
   - Matrix: `tf.constant([[1, 2], [3, 4]])`

2. **Graphs (Computational Graphs):** TensorFlow uses a computational graph to define and execute operations (ops). A computational graph is a directed acyclic graph (DAG) where nodes represent operations, and edges represent the flow of data (tensors) between operations. The graph defines the structure of a model or computation without performing it until explicitly executed. The `tf.Graph` class is used to create and manage these graphs.

   Example:
   ```python
   import tensorflow as tf

   # Create a computational graph
   graph = tf.Graph()
   with graph.as_default():
       a = tf.constant(2)
       b = tf.constant(3)
       c = tf.add(a, b)

   # Execute the graph
   with tf.Session(graph=graph) as sess:
       result = sess.run(c)
       print(result)  # Output: 5
   ```

In addition to these fundamental data structures, TensorFlow provides higher-level abstractions like `tf.Variable` for trainable variables, `tf.placeholder` for feedable data, and various specialized data structures for handling sequences (e.g., `tf.TensorArray`) and more complex data types. These data structures are used to build and manipulate models for machine learning and deep learning tasks.

#### 2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

In TensorFlow, both constants and variables are used to represent data or values within a computation graph. However, they have key differences:

1. **TensorFlow Constants:**
   - Constants are tensors whose values cannot be changed once they are defined. They are immutable.
   - They are primarily used to represent fixed values, such as hyperparameters, input data, or constants in mathematical operations.
   - Constants are typically used for values that remain constant throughout the execution of a TensorFlow program.

   Example:
   ```python
   import tensorflow as tf

   # Creating a constant
   a = tf.constant(5)
   b = tf.constant(3)

   # Operations with constants
   c = tf.add(a, b)

   # Running the computation
   with tf.Session() as sess:
       result = sess.run(c)
       print(result)  # Output: 8
   ```

2. **TensorFlow Variables:**
   - Variables are tensors whose values can be changed during the execution of a TensorFlow program.
   - They are primarily used to represent model parameters that need to be updated during training, such as weights and biases in a neural network.
   - Variables have an initial value but can be modified using operations like `assign` or `assign_add`.

   Example:
   ```python
   import tensorflow as tf

   # Creating a variable
   initial_value = tf.constant(2.0)
   my_variable = tf.Variable(initial_value)

   # Operations to modify the variable
   new_value = tf.add(my_variable, tf.constant(1.0))
   update_operation = tf.assign(my_variable, new_value)

   # Running the computation
   with tf.Session() as sess:
       sess.run(tf.global_variables_initializer())  # Initialize variables
       print(sess.run(my_variable))  # Output: 2.0

       # Update the variable
       sess.run(update_operation)
       print(sess.run(my_variable))  # Output: 3.0
   ```

In summary, constants are used for fixed values, while variables are used for values that can change during computation, making them suitable for model training where parameters are updated iteratively.

#### 3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

TensorFlow provides operations for performing various matrix operations, including addition, multiplication, and element-wise operations. Here's an overview of these operations in TensorFlow:

1. **Matrix Addition:**
   - Matrix addition is performed using the `tf.add()` function. It adds two tensors of the same shape element-wise.
   - Both tensors must have the same shape (i.e., the same number of rows and columns).
   - The result is a new tensor of the same shape as the input tensors, where each element is the sum of the corresponding elements in the input tensors.

   Example:
   ```python
   import tensorflow as tf

   # Define two matrices
   matrix1 = tf.constant([[1, 2], [3, 4]])
   matrix2 = tf.constant([[5, 6], [7, 8]])

   # Perform matrix addition
   result = tf.add(matrix1, matrix2)

   with tf.Session() as sess:
       print(sess.run(result))
       # Output:
       # [[ 6  8]
       #  [10 12]]
   ```

2. **Matrix Multiplication:**
   - Matrix multiplication is performed using the `tf.matmul()` function. It computes the matrix product of two tensors.
   - The matrices must be compatible for multiplication, meaning the number of columns in the first matrix must match the number of rows in the second matrix.
   - The result is a new tensor with dimensions determined by the matrix multiplication.

   Example:
   ```python
   import tensorflow as tf

   # Define two matrices
   matrix1 = tf.constant([[1, 2], [3, 4]])
   matrix2 = tf.constant([[5, 6], [7, 8]])

   # Perform matrix multiplication
   result = tf.matmul(matrix1, matrix2)

   with tf.Session() as sess:
       print(sess.run(result))
       # Output:
       # [[19 22]
       #  [43 50]]
   ```

3. **Element-Wise Operations:**
   - Element-wise operations are performed on corresponding elements of tensors without any regard for their shapes, as long as they have compatible shapes or can be broadcasted.
   - Common element-wise operations include addition, subtraction, multiplication, and division, and they use operators like `+`, `-`, `*`, and `/`.

   Example (element-wise multiplication):
   ```python
   import tensorflow as tf

   # Define two tensors
   tensor1 = tf.constant([1, 2, 3])
   tensor2 = tf.constant([4, 5, 6])

   # Perform element-wise multiplication
   result = tf.multiply(tensor1, tensor2)

   with tf.Session() as sess:
       print(sess.run(result))
       # Output: [ 4 10 18]
   ```

TensorFlow's ability to perform these matrix operations efficiently is crucial for implementing neural networks and other machine learning models where large-scale matrix computations are common.

### Part 2: Practical Implementation:
### Task 1: Creating and Manipulating Matrices

#### 1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.

In [19]:
import tensorflow as tf

# Create a 2x2 matrix with random values from a normal distribution
matrix_A = tf.random.normal(shape=(2, 2), mean=0.0, stddev=1.0, dtype=tf.float32)

# Display the values of matrix A
print("Matrix A:")
print(matrix_A.numpy())

Matrix A:
[[-1.3927959  -0.69048923]
 [-0.25704437 -0.45764235]]


#### 2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B.

In [20]:
import tensorflow as tf

# Create a 4x4 matrix with random values from a truncated normal distribution
matrix_B = tf.random.truncated_normal(shape=(4, 4), mean=0.0, stddev=1.0, dtype=tf.float32)

# Display the values of matrix B
print("Matrix B:")
print(matrix_B.numpy())

Matrix B:
[[ 0.28433803 -0.3378609   0.297738    0.86040425]
 [-1.7358208   0.5555191   1.6036378  -0.27442893]
 [-0.9305784  -1.3455914   1.021067   -0.89564586]
 [-0.20929965  0.86583906 -1.2110511   1.2210139 ]]


#### 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

In [21]:
import tensorflow as tf

# Create a 2x2 matrix with random values from a normal distribution
mean = 2.0
stddev = 0.5
matrix_C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev, dtype=tf.float32)

# Display the values of matrix C
print("Matrix C:")
print(matrix_C.numpy())


Matrix C:
[[1.6529593 1.3991985]
 [2.434399  1.9666162]]


#### 4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

In [28]:


# Create matrix A
matrix_A = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)

# Create matrix B
matrix_B = tf.constant([[0.5, 1.0], [1.5, 2.0]], dtype=tf.float32)

# Perform matrix addition
matrix_D = tf.add(matrix_A, matrix_B)

# Display the result (matrix D)
print("Matrix D (Result of Addition):")
print(matrix_D.numpy())


Matrix D (Result of Addition):
[[1.5 3. ]
 [4.5 6. ]]


#### 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [29]:
# Perform matrix multiplication
matrix_E = tf.matmul(matrix_C, matrix_D)

# Display the result (matrix E)
print("Matrix E (Result of Multiplication):")
print(matrix_E.numpy())

Matrix E (Result of Multiplication):
[[ 8.775832 13.354069]
 [12.501371 19.102894]]


### Talk 2: Performing Additional Matrix Operations

#### 1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.

In [36]:
import tensorflow as tf

# Create a 2x2 matrix with random values from a uniform distribution
matrix_F = tf.random.uniform(shape=(2, 2), minval=0.0, maxval=1.0, dtype=tf.float32)

# Display the values of matrix F
print("Matrix F:")
print(matrix_F.numpy())


Matrix F:
[[0.6375506  0.2738427 ]
 [0.02895403 0.98305047]]


#### 2. Calculate the transpose of matrix F and store the result in matrix G.

In [37]:
# Calculate the transpose of matrix F
matrix_G = tf.transpose(matrix_F)

# Display the values of matrix F and matrix G
print("Matrix F:")
print(matrix_F.numpy())

print("\nMatrix G (Transpose of F):")
print(matrix_G.numpy())

Matrix F:
[[0.6375506  0.2738427 ]
 [0.02895403 0.98305047]]

Matrix G (Transpose of F):
[[0.6375506  0.02895403]
 [0.2738427  0.98305047]]


#### 3. Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [38]:
import tensorflow as tf

# Calculate element-wise exponential of matrix F
matrix_H = tf.exp(matrix_F)

# Display the values of matrix F and matrix H
print("Matrix F:")
print(matrix_F.numpy())

print("\nMatrix H (Element-wise Exponential of F):")
print(matrix_H.numpy())


Matrix F:
[[0.6375506  0.2738427 ]
 [0.02895403 0.98305047]]

Matrix H (Element-wise Exponential of F):
[[1.8918413 1.3150079]
 [1.0293772 2.6725965]]


#### 4. Create a matrix I by concatenating matrix F and matrix G horizontally.

In [39]:
# Concatenate matrix F and matrix G horizontally
matrix_I = tf.concat([matrix_F, matrix_G], axis=1)

# Display the values of matrix F, matrix G, and matrix I
print("Matrix F:")
print(matrix_F.numpy())

print("\nMatrix G (Transpose of F):")
print(matrix_G.numpy())

print("\nMatrix I (Concatenation of F and G Horizontally):")
print(matrix_I.numpy())

Matrix F:
[[0.6375506  0.2738427 ]
 [0.02895403 0.98305047]]

Matrix G (Transpose of F):
[[0.6375506  0.02895403]
 [0.2738427  0.98305047]]

Matrix I (Concatenation of F and G Horizontally):
[[0.6375506  0.2738427  0.6375506  0.02895403]
 [0.02895403 0.98305047 0.2738427  0.98305047]]


#### 5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [40]:
# Concatenate matrix F and matrix H vertically
matrix_J = tf.concat([matrix_F, matrix_H], axis=0)

# Display the values of matrix F, matrix H, and matrix J
print("Matrix F:")
print(matrix_F.numpy())

print("\nMatrix H (Element-wise Exponential of F):")
print(matrix_H.numpy())

print("\nMatrix J (Concatenation of F and H Vertically):")
print(matrix_J.numpy())

Matrix F:
[[0.6375506  0.2738427 ]
 [0.02895403 0.98305047]]

Matrix H (Element-wise Exponential of F):
[[1.8918413 1.3150079]
 [1.0293772 2.6725965]]

Matrix J (Concatenation of F and H Vertically):
[[0.6375506  0.2738427 ]
 [0.02895403 0.98305047]
 [1.8918413  1.3150079 ]
 [1.0293772  2.6725965 ]]
